name: Build and Deploy to ACR + VM

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/tomcat-app:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/tomcat-app:${{ github.sha }}